apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-headless-loadgen
  namespace: easytravel
  labels:
    app: easytravel-k8s
    type: headless-loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytravel-k8s
      type: headless-loadgen
  template:
    metadata:
      labels:
        app: easytravel-k8s
        type: headless-loadgen
    spec:
      containers:
      - name: easytravel-headless-loadgen
        image: dynatrace/easytravel-headless-loadgen:2.0.0.3322
        ports:
        - containerPort: 8080
        env:
        - name: ET_ANGULAR_FRONTEND_URL
          value: http://easytravel-angular-frontend:80
        - name: ET_BACKEND_URL
          value: http://easytravel-backend:8080
        - name: ET_APM_SERVER_DEFAULT
          value: APM
        - name: ET_PROBLEMS
          value: DatabaseCleanup
        - name: ET_PROBLEMS_DELAY
          value: "0"
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          # requests:
          #   cpu: 200m
          #   memory: 256Mi
