apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-www
  namespace: easytravel
  labels:
    app: easytravel-k8s
    type: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytravel-k8s
      type: www
  template:
    metadata:
      labels:
        app: easytravel-k8s
        type: www
    spec:
      containers:
      - name: easytravel-www
        image: dynatrace/easytravel-nginx:2.0.0.3322
        ports:
        - containerPort: 80
        env:
        - name: ET_FRONTEND_LOCATION
          value: easytravel-frontend:8080
        - name: ET_BACKEND_LOCATION
          value: easytravel-backend:8080
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-www
  namespace: easytravel
  labels:
    app: easytravel-k8s
    type: www
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: easytravel-k8s
    type: www