apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-frontend
  namespace: easytravel
  labels:
    app: easytravel-k8s
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytravel-k8s
      type: frontend
  template:
    metadata:
      labels:
        app: easytravel-k8s
        type: frontend
    spec:
      containers:
      - name: easytravel-frontend
        image: dynatrace/easytravel-frontend:2.0.0.3322
        ports:
        - containerPort: 8080
        env:
        - name: CATALINA_OPTS
          value: -Dconfig.apmServerDefault=APM -Xmx525m
        - name: ET_BACKEND_URL
          value: http://easytravel-backend:8080
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
          # requests:
          #   cpu: 200m
          #   memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-frontend
  namespace: easytravel
  labels:
    app: easytravel-k8s
    type: frontend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: easytravel-k8s
    type: frontend