apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-www
  namespace: easytravel
  labels:
    app: easytravel-k8s
    type: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytravel-k8s
      type: www
  template:
    metadata:
      labels:
        app: easytravel-k8s
        app.kubernetes.io/part-of: easytravel
        app.kubernetes.io/version: "1.0.0"
        type: www
    spec:
      containers:
      - name: easytravel-www
        image: dynatrace/easytravel-nginx:2.0.0.3356
        ports:
        - containerPort: 80
        - containerPort: 8080
        env:
        - name: ET_FRONTEND_LOCATION
          value: easytravel-frontend:8080
        - name: ET_BACKEND_LOCATION
          value: easytravel-backend:8080
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          # requests:
          #   cpu: 200m
          #   memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-www
  namespace: easytravel
  labels:
    app: easytravel-k8s
    type: www
spec:
  type: LoadBalancer
  ports:
  - name: frontend
    port: 80
    targetPort: 80
  - name: backend
    port: 8080
    targetPort: 8080
  selector:
    app: easytravel-k8s
    type: www