apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-mongodb
  namespace: easytravel
  labels:
    app: easytravel-k8s
    type: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytravel-k8s
      type: mongodb
  template:
    metadata:
      labels:
        app: easytravel-k8s
        type: mongodb
    spec:
      containers:
      - name: easytravel-mongodb
        image: dynatrace/easytravel-mongodb:2.0.0.3322
        ports:
        - containerPort: 27017
        - containerPort: 28017
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          # requests:
          #   cpu: 200m
          #   memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-mongodb
  namespace: easytravel
  labels:
    app: easytravel-k8s
    type: mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
    protocol: TCP
  - name: "28017"
    port: 28017
    targetPort: 28017
    protocol: TCP
  selector:
    app: easytravel-k8s
    type: mongodb